const common = @import("common");
const libx11 = @import("x11/xlib.zig");
const ScanCode = common.keyboard_and_mouse.ScanCode;
const KeyCode = common.keyboard_and_mouse.KeyCode;

pub const SCANCODE_LOOKUP_TABLE = [256]ScanCode{
    // the first 8 are never produced by the xserver.
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Escape,
    ScanCode.Num1,
    ScanCode.Num2,
    ScanCode.Num3,
    ScanCode.Num4,
    ScanCode.Num5,
    ScanCode.Num6,
    ScanCode.Num7,
    ScanCode.Num8,
    ScanCode.Num9,
    ScanCode.Num0,
    ScanCode.Hyphen,
    ScanCode.Equal,
    ScanCode.Backspace,
    ScanCode.Tab,
    ScanCode.Q,
    ScanCode.W,
    ScanCode.E,
    ScanCode.R,
    ScanCode.T,
    ScanCode.Y,
    ScanCode.U,
    ScanCode.I,
    ScanCode.O,
    ScanCode.P,
    ScanCode.LBracket,
    ScanCode.RBracket,
    ScanCode.Return,
    ScanCode.LControl,
    ScanCode.A,
    ScanCode.S,
    ScanCode.D,
    ScanCode.F,
    ScanCode.G,
    ScanCode.H,
    ScanCode.J,
    ScanCode.K,
    ScanCode.L,
    ScanCode.Semicolon,
    ScanCode.Quote,
    ScanCode.Grave,
    ScanCode.LShift,
    ScanCode.Backslash,
    ScanCode.Z,
    ScanCode.X,
    ScanCode.C,
    ScanCode.V,
    ScanCode.B,
    ScanCode.N,
    ScanCode.M,
    ScanCode.Comma,
    ScanCode.Period,
    ScanCode.Slash,
    ScanCode.RShift,
    ScanCode.NumpadMultiply,
    ScanCode.LAlt,
    ScanCode.Space,
    ScanCode.CapsLock,
    ScanCode.F1,
    ScanCode.F2,
    ScanCode.F3,
    ScanCode.F4,
    ScanCode.F5,
    ScanCode.F6,
    ScanCode.F7,
    ScanCode.F8,
    ScanCode.F9,
    ScanCode.F10,
    ScanCode.NumLock,
    ScanCode.ScrollLock,
    ScanCode.Numpad7,
    ScanCode.Numpad8,
    ScanCode.Numpad9,
    ScanCode.NumpadSubtract,
    ScanCode.Numpad4,
    ScanCode.Numpad5,
    ScanCode.Numpad6,
    ScanCode.NumpadAdd,
    ScanCode.Numpad1,
    ScanCode.Numpad2,
    ScanCode.Numpad3,
    ScanCode.Numpad0,
    ScanCode.NumpadDecimal,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Key102nd,
    ScanCode.F11,
    ScanCode.F12,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.NumpadReturn,
    ScanCode.RControl,
    ScanCode.NumpadDivide,
    ScanCode.PrintScreen,
    ScanCode.RAlt,
    ScanCode.Return, // LineFeed
    ScanCode.Home,
    ScanCode.Up,
    ScanCode.PageUp,
    ScanCode.Left,
    ScanCode.Right,
    ScanCode.End,
    ScanCode.Down,
    ScanCode.PageDown,
    ScanCode.Insert,
    ScanCode.Delete,
    ScanCode.Unknown, // Macro
    ScanCode.VolumeMute,
    ScanCode.VolumeDown,
    ScanCode.VolumeUp,
    ScanCode.Unknown, // Power
    ScanCode.NumpadEqual,
    ScanCode.Unknown,
    ScanCode.Pause,
    ScanCode.Unknown,
    ScanCode.NumpadDecimal,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Menu,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.NextTrack,
    ScanCode.PlayPause,
    ScanCode.PrevTrack,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown, // start F13 to F24
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown, // end of F13 to f24
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
    ScanCode.Unknown,
};

pub fn mapXKeySymToWidowKeyCode(keysym: libx11.KeySym) KeyCode {
    return switch (keysym) {
        libx11.XK_Escape => KeyCode.Escape,
        libx11.XK_Tab => KeyCode.Tab,
        libx11.XK_BackSpace => KeyCode.Backspace,
        libx11.XK_Return => KeyCode.Return,
        libx11.XK_Insert => KeyCode.Insert,
        libx11.XK_Delete => KeyCode.Delete,
        libx11.XK_Clear => KeyCode.Delete,
        libx11.XK_Pause => KeyCode.Pause,
        // libx11.XK_Print => KeyCode.PRINT,
        libx11.XK_Home => KeyCode.Home,
        libx11.XK_End => KeyCode.End,
        libx11.XK_Left => KeyCode.Left,
        libx11.XK_Up => KeyCode.Up,
        libx11.XK_Right => KeyCode.Right,
        libx11.XK_Down => KeyCode.Down,
        libx11.XK_Prior => KeyCode.PageUp,
        libx11.XK_Next => KeyCode.PageDown,
        libx11.XK_Shift_L => KeyCode.Shift,
        libx11.XK_Shift_R => KeyCode.Shift,
        libx11.XK_Shift_Lock => KeyCode.Shift,
        libx11.XK_Control_L => KeyCode.Control,
        libx11.XK_Control_R => KeyCode.Control,
        libx11.XK_Meta_L => KeyCode.Meta,
        libx11.XK_Meta_R => KeyCode.Meta,
        libx11.XK_Alt_L => KeyCode.Alt,
        libx11.XK_Alt_R => KeyCode.Alt,
        libx11.XK_Caps_Lock => KeyCode.CapsLock,
        libx11.XK_Num_Lock => KeyCode.NumLock,
        libx11.XK_Scroll_Lock => KeyCode.ScrollLock,
        libx11.XK_less => KeyCode.Quote,
        libx11.XK_grave => KeyCode.Grave,
        libx11.XK_Super_L => KeyCode.Meta,
        libx11.XK_Super_R => KeyCode.Meta,
        libx11.XK_Menu => KeyCode.Menu,
        // libx11.XK_Help => KeyCode.HELP,
        libx11.XK_KP_Space => KeyCode.Space,
        libx11.XK_KP_Tab => KeyCode.Tab,
        libx11.XK_KP_Enter => KeyCode.Return,
        // libx11.XK_Begin => KeyCode.CLEAR,
        libx11.XK_KP_Equal => KeyCode.Equal,
        libx11.XK_KP_Separator => KeyCode.Comma,
        libx11.XK_KP_Decimal => KeyCode.Period,
        libx11.XK_KP_Multiply => KeyCode.Multiply,
        libx11.XK_KP_Divide => KeyCode.Divide,
        libx11.XK_KP_Subtract => KeyCode.Subtract,
        libx11.XK_KP_Add => KeyCode.Add,
        libx11.XK_KP_0 => KeyCode.Numpad0,
        libx11.XK_KP_1 => KeyCode.Numpad1,
        libx11.XK_KP_2 => KeyCode.Numpad2,
        libx11.XK_KP_3 => KeyCode.Numpad3,
        libx11.XK_KP_4 => KeyCode.Numpad4,
        libx11.XK_KP_5 => KeyCode.Numpad5,
        libx11.XK_KP_6 => KeyCode.Numpad6,
        libx11.XK_KP_7 => KeyCode.Numpad7,
        libx11.XK_KP_8 => KeyCode.Numpad8,
        libx11.XK_KP_9 => KeyCode.Numpad9,
        // Same keys but with numlock off.
        libx11.XK_KP_Insert => KeyCode.Insert,
        libx11.XK_KP_Delete => KeyCode.Delete,
        libx11.XK_KP_End => KeyCode.End,
        libx11.XK_KP_Down => KeyCode.Down,
        libx11.XK_KP_Page_Down => KeyCode.PageDown,
        libx11.XK_KP_Left => KeyCode.Left,
        libx11.XK_KP_Right => KeyCode.Right,
        libx11.XK_KP_Home => KeyCode.Home,
        libx11.XK_KP_Up => KeyCode.Up,
        libx11.XK_KP_Page_Up => KeyCode.PageUp,
        libx11.XK_F1 => KeyCode.F1,
        libx11.XK_F2 => KeyCode.F2,
        libx11.XK_F3 => KeyCode.F3,
        libx11.XK_F4 => KeyCode.F4,
        libx11.XK_F5 => KeyCode.F5,
        libx11.XK_F6 => KeyCode.F6,
        libx11.XK_F7 => KeyCode.F7,
        libx11.XK_F8 => KeyCode.F8,
        libx11.XK_F9 => KeyCode.F9,
        libx11.XK_F10 => KeyCode.F10,
        libx11.XK_F11 => KeyCode.F11,
        libx11.XK_F12 => KeyCode.F12,
        // libx11.XK_F13 => KeyCode.F13,
        // libx11.XK_F14 => KeyCode.F14,
        // libx11.XK_F15 => KeyCode.F15,
        // libx11.XK_F16 => KeyCode.F16,
        // libx11.XK_F17 => KeyCode.F17,
        // libx11.XK_F18 => KeyCode.F18,
        // libx11.XK_F19 => KeyCode.F19,
        // libx11.XK_F20 => KeyCode.F20,
        // libx11.XK_F21 => KeyCode.F21,
        // libx11.XK_F22 => KeyCode.F22,
        // libx11.XK_F23 => KeyCode.F23,
        // libx11.XK_F24 => KeyCode.F24,
        // libx11.XK_F25 => KeyCode.F25,
        // libx11.XK_F26 => KeyCode.F26,
        // libx11.XK_F27 => KeyCode.F27,
        // libx11.XK_F28 => KeyCode.F28,
        // libx11.XK_F29 => KeyCode.F29,
        // libx11.XK_F30 => KeyCode.F30,
        // libx11.XK_F31 => KeyCode.F31,
        // libx11.XK_F32 => KeyCode.F32,
        // libx11.XK_F33 => KeyCode.F33,
        // libx11.XK_F34 => KeyCode.F34,
        // libx11.XK_F35 => KeyCode.F35,
        // libx11.XK_yen => KeyCode.YEN,
        libx11.XF86XK_AudioLowerVolume => KeyCode.VolumeDown,
        libx11.XF86XK_AudioMute => KeyCode.VolumeMute,
        libx11.XF86XK_AudioRaiseVolume => KeyCode.VolumeUp,
        libx11.XF86XK_AudioPlay => KeyCode.PlayPause,
        libx11.XF86XK_AudioStop => KeyCode.PlayPause,
        libx11.XF86XK_AudioPrev => KeyCode.PrevTrack,
        libx11.XF86XK_AudioNext => KeyCode.NextTrack,
        else => KeyCode.Unknown,
    };
}
